- job_name: 'dfr_backup_status'
  metrics_path: /metrics # Path for the backup status exporter
  static_configs:
    - targets: ['backup_monitor_host:9901'] # Placeholder for the backup status exporter endpoint
      labels:
        env: 'production'