- job_name: 'dfr_postgres_db'
  metrics_path: /metrics
  static_configs:
    - targets: ['postgres_exporter_instance1_host:9187', 'postgres_exporter_instance2_host:9187'] # Placeholder for actual exporter endpoints
      labels:
        env: 'production'
        country: 'CKI'