name: dfr_mobile
description: DFR Mobile Enumerator Application.
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1 # Adhering to SemVer REQ-CM-003

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  
  # HTTP Client
  dio: ^5.4.0

  # Local Database
  sqflite: ^2.3.0 
  # For SQLCipher, sqlcipher_flutter_libs provides native libs.
  # The actual Flutter package to use sqflite with SQLCipher is often sqflite_sqlcipher or a similar wrapper.
  # As per SDS, using sqflite and sqlcipher_flutter_libs.
  # If a direct package like sqflite_sqlcipher is used, this might change.
  # For now, assuming sqflite can be configured for SQLCipher with these libs.
  # A common package that bundles this is `sqflite_sqlcipher`
  # Using `sqflite` directly and will rely on native bindings for SQLCipher if that's the chosen path,
  # or this will be replaced by `sqflite_sqlcipher` if it's the package used.
  # For the purpose of this generation, we'll list sqflite and assume SQLCipher is handled via pragma/native.
  sqlcipher_flutter_libs: ^0.6.0 # Provides SQLCipher native libraries

  # Secure Storage
  flutter_secure_storage: ^9.0.0

  # GPS
  geolocator: ^12.0.0

  # QR Scanner
  mobile_scanner: ^5.1.0

  # Connectivity
  connectivity_plus: ^6.0.3

  # Filesystem Paths
  path_provider: ^2.1.1

  # UUID Generation
  uuid: ^4.3.3

  # Internationalization & Localization
  intl: ^0.19.0

  # Dependency Injection
  get_it: ^7.6.7

  # Functional Programming (Either, Option)
  dartz: ^0.10.1

  # Value Equality
  equatable: ^2.0.5

  # Logging
  logger: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.8
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # Asset directories
    - assets/images/
    - assets/fonts/
    # Localization files
    - assets/i18n/
    # Add other assets here

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700