groups:
- name: general_system_alerts
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: critical
      service: system
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
  - alert: HighCpuUsage
    expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 90
    for: 10m
    labels:
      severity: warning
      service: system
    annotations:
      summary: "High CPU usage on {{ $labels.instance }}"
      description: "CPU usage is {{ $value | printf \"%.2f\" }}% on instance {{ $labels.instance }} for more than 10 minutes."
  - alert: LowMemoryAvailable
    expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100) < 10
    for: 5m
    labels:
      severity: critical
      service: system
    annotations:
      summary: "Low memory available on {{ $labels.instance }}"
      description: "Less than 10% ({{ $value | printf \"%.2f\" }}%) memory available on instance {{ $labels.instance }}."
  - alert: LowDiskSpace
    expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} * 100) < 10
    for: 1h # Less frequent check as disk space changes slower
    labels:
      severity: critical
      service: system
    annotations:
      summary: "Low disk space on {{ $labels.instance }} (mountpoint /)"
      description: "Less than 10% ({{ $value | printf \"%.2f\" }}%) disk space available on {{ $labels.instance }} for mountpoint /."