groups:
- name: odoo_application_alerts
  rules:
  - alert: OdooHighErrorRate
    expr: sum(rate(odoo_http_requests_total{status=~"5.."}[5m])) by (instance, job, country) / sum(rate(odoo_http_requests_total[5m])) by (instance, job, country) * 100 > 5
    for: 5m
    labels:
      severity: critical
      service: odoo
    annotations:
      summary: "High Odoo HTTP 5xx error rate on {{ $labels.instance }} (Country: {{ $labels.country }})"
      description: "Odoo instance {{ $labels.instance }} is experiencing an error rate of {{ $value | printf \"%.2f\" }}%."
  - alert: OdooSlowResponseTime
    # This metric would ideally come from a custom exporter or odoo_prometheus_exporter
    # Example: odoo_http_request_duration_seconds_bucket
    expr: histogram_quantile(0.95, sum(rate(odoo_http_request_duration_seconds_bucket[5m])) by (le, instance, job, country)) > 2
    for: 10m
    labels:
      severity: warning
      service: odoo
    annotations:
      summary: "Slow Odoo response time on {{ $labels.instance }} (Country: {{ $labels.country }})"
      description: "95th percentile Odoo response time is above 2s on {{ $labels.instance }}."
  # Add alerts for Odoo worker availability if metrics are available
  # Example: odoo_running_workers < odoo_configured_workers * 0.5